export type ExamType = 
  | 'Self Evaluation Test' 
  | 'Weekly Test' 
  | 'Monthly Test' 
  | 'Terminal' 
  | 'Scholarship Exam';

export interface ExamMark {
  examType: ExamType;
  obtainedScore?: number; // Undefined if not entered yet
  totalScore: number;     // Configured per exam type
  passScore: number;      // Configured per exam type
  remarks?: string;
  dateEntered?: string;
}

export interface SubjectMark {
  subject: string;
  exams: ExamMark[]; // One for each of the 5 exam types
}

export interface AttendanceRecord {
  date: string;
  status: 'Present' | 'Absent' | 'Late';
}

export interface Student {
  id: string;            // Enrollment number or Unique ID
  username: string;      // Set by Admin
  name: string;
  gradeClass: string;    // "Class 1" to "Class 12"
  password: string;      // Can be generated by students themselves
  subjects: string[];    // Array of active subjects (Compulsory Maths, Optional Maths, Science, etc)
  marksBySubject: SubjectMark[]; // Subject-wise exams
  attendance: AttendanceRecord[];
  isResultWithheld: boolean; // Managed by Admin
  generalRemarks?: string;
}

export interface Teacher {
  id: string;
  name: string;
  username: string;
  password: string;
}

export interface Announcement {
  id: string;
  title: string;
  content: string;
  date: string;
  priority: 'low' | 'medium' | 'high';
  category: 'Academics' | 'Events' | 'Holiday' | 'Sports' | 'General';
  active: boolean;
}

export interface StudyMaterial {
  id: string;
  title: string;
  gradeClass: string; // e.g. "Class 10" or "All"
  subject: string;    // e.g. "Science" or "All"
  fileName: string;
  fileSize: string;
  downloadUrl: string;
  uploadDate: string;
}
